blueprint:
  name: ZHA - IKEA Styrbar - Color Lights (No Helper) - Fixed2
  description: >-
    Control IKEA Color bulbs using an IKEA Styrbar remote via ZHA.
    Up: Turn On / Increase Brightness
    Down: Turn Off / Decrease Brightness
    Left/Right: Cycle Color Hue
  domain: automation
  input:
    remote:
      name: IKEA Styrbar remote
      description: Select the remote control (E2313 / E2001).
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
    light_target:
      name: Light
      description: Select the color light to control.
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # --- UP BUTTON ---
      - conditions:
          - "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target

      # Long Press Up: Dim Up
      - conditions
