blueprint:
  name: ZHA - IKEA Styrbar (E2313) - Color Cycling
  description: >
    Reworked version of niro1987's 5-button blueprint for the 4-button Styrbar.
    - Up: Toggle Light (Short), Reset to default (Long)
    - Down: Dimming (Hold)
    - Left/Right: Cycle through Color Presets
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA Styrbar remote to use
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light
    color_helper:
      name: Color Helper
      description: Input Select helper containing your color presets (e.g. "255,100,50")
      selector:
        entity:
          domain: input_select

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"

  - choose:
      # UP BUTTON (Short Press) -> TOGGLE
      - conditions:
          - "{{ command == 'on' }}"
        sequence:
          - service: light.toggle
            target: !input light

      # UP BUTTON (Long Press) -> RESET
      - conditions:
          - "{{ command == 'move_to_level_with_on_off' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness: 254
              kelvin: 2700

      # DOWN BUTTON (Short Press) -> TURN OFF
      - conditions:
          - "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target: !input light

      # LEFT BUTTON (Short Press) -> PREVIOUS PRESET
      - conditions:
          - "{{ command == 'press' and trigger.event.data.params.param1 == 257 }}"
        sequence:
          - service: input_select.select_previous
            target:
              entity_id: !input color_helper
          - service: light.turn_on
            target: !input light
            data:
              rgb_color: "{{ states(color_helper).split(',') | map('int') | list }}"

      # RIGHT BUTTON (Short Press) -> NEXT PRESET
      - conditions:
          - "{{ command == 'press' and trigger.event.data.params.param1 == 256 }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input color_helper
          - service: light.turn_on
            target: !input light
            data:
              rgb_color: "{{ states(color_helper).split(',') | map('int') | list }}"

      # BRIGHTNESS UP (Hold Up)
      - conditions:
          - "{{ command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: 500

      # BRIGHTNESS DOWN (Hold Down)
      - conditions:
          - "{{ command == 'move' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: 500
